MONGODB_HOST: mongodb.daws86s.icu
REDIS_HOST: redis.daws86s.icu
CATALOGUE_HOST: catalogue.daws86s.icu
CART_HOST: cart.daws86s.icu
USER_HOST: user.daws86s.icu
RABBITMQ_HOST: rabbitmq.daws86s.icu
MYSQL_HOST: mysql.daws86s.icu
SHIPPING_HOST: shipping.daws86s.icu
PAYMENT_HOST: payment.daws86s.icu