    
- name: Add the user roboshop
  ansible.builtin.user:
    name: roboshop
    comment: system user roboshop
    system: true
    shell: /sbin/nologin
    home: /app

- name: Remove app directory
  ansible.builtin.file:
    path: /app
    state: absent    

- name: Create app directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory

- name: delete {{ component }} file
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: Download {{ component }} zip
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

- name: Extract {{ component }} zip
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes
